# Everything we know about every part of the SO-ARM101 follower arm.
# Sources: TheRobotStudio/SO-ARM100 README + URDF (Apache-2.0), Feetech STS3215
# datasheet figures as quoted in the README, Waveshare product page.
# Prices are the README's US column, Sept 2026. Printed masses are estimates
# from mesh volume x PLA density x ~45% (walls + 20% infill).

PLA_DENSITY = 1.24      # g/cm3
PRINT_FILL = 0.45       # effective solid fraction with 20% infill and 3 walls

SERVO = {
    'name': 'Feetech STS3215 serial bus servo (7.4 V, 1:345)',
    'short': 'STS3215 servo',
    'category': 'actuator',
    'mass_g': 60,
    'price_usd': 13.89,
    'made_of': 'Aluminium/plastic case, metal gears, coreless DC motor, PCB',
    'what': 'A smart motor. It is a small DC motor, a 345:1 gearbox, a position sensor and a tiny computer in one box. You tell it an angle over a serial cable and it goes there and holds.',
    'why': 'Six of these are the entire muscle system of the arm. There are no separate motor drivers, encoders or wiring harnesses because each servo contains its own. That is what makes a $120 robot arm possible.',
    'spec': [
        ['Stall torque', '16.5 kg·cm ≈ 1.6 N·m at 6 V (30 kg·cm for the 12 V version)'],
        ['Speed', '≈ 0.22 s per 60° at 7.4 V'],
        ['Position sensor', '12-bit magnetic encoder, 4,096 steps per turn'],
        ['Control', 'TTL serial bus, 1 Mbps, daisy-chained; each servo has an ID'],
        ['Voltage', '6–7.4 V (12 V variant available)'],
        ['Gear ratio', '1:345 metal gears'],
        ['Modes', 'position, constant speed, PWM; reports position, load, temperature, voltage'],
    ],
    'inside': [
        ['Coreless DC motor', 'Spins at thousands of rpm with almost no torque. Everything else exists to slow it down and make it precise.'],
        ['Metal gear train (1:345)', 'Five stages of gears trade speed for torque: 345 turns of the motor = 1 turn of the output horn.'],
        ['Magnetic encoder (12-bit)', 'A magnet on the output shaft and a Hall-effect chip read the angle to 1/4096 of a turn — the servo always knows where it is, even after power loss.'],
        ['Control MCU', 'A microcontroller runs the position loop hundreds of times a second and speaks the serial protocol.'],
        ['H-bridge driver (MOSFETs)', 'Four transistors switch battery current into the motor in either direction.'],
        ['Case, bearing and output horn', 'The horn is the splined disc the printed parts bolt to; a bearing takes side loads off the gears.'],
    ],
    'remove': 'Remove one and that joint goes limp — the arm folds under gravity at that point. Swap in the 12 V version and every joint gets almost twice the torque, for a 12 V supply.',
    'buy': 'https://www.alibaba.com/product-detail/Top-Seller-Low-Cost-Feetech-STS3215_1600999461525.html',
}

PRINTED_COMMON = dict(category='structure', made_of='PLA+ plastic, FDM 3D-printed, 20% infill',
                      print='PLA+, 0.2 mm layers, 20% infill, no supports needed in screw holes')

PARTS = {
    'base_so101_v2': dict(PRINTED_COMMON, name='Base', volume_key='base_so101_v2',
        what='The foot of the arm. A wide, flat printed shell that sits on the table and holds the first servo pointing straight up.',
        why='Everything else hangs off this. Its width is what stops the arm tipping over when it reaches out; the table clamp bolts through it.',
        remove='Without it there is nothing to clamp down — the whole arm becomes a loose chain on the table.'),
    'base_motor_holder_so101_v1': dict(PRINTED_COMMON, name='Base motor holder',
        what='A cradle inside the base that grips the shoulder-pan servo body with four small screws.',
        why='Servos have no mounting flange of their own; every servo in this arm sits in a printed cradle like this one.',
        remove='The first servo would rattle loose in the base and the whole arm would wobble on its axis.'),
    'motor_holder_so101_base_v1': dict(PRINTED_COMMON, name='Shoulder motor holder',
        what='Cradle for the shoulder-lift servo. It bolts onto the output horn of the servo below, so it turns when the base servo turns.',
        why='This is where rotation about the vertical axis is passed upward: the holder is the first moving part.',
        remove='The shoulder-lift servo has nothing to sit in; the arm above the base falls off.'),
    'rotation_pitch_so101_v1': dict(PRINTED_COMMON, name='Shoulder pitch bracket',
        what='The bracket that turns the shoulder-lift servo output into a pivot for the upper arm.',
        why='It carries the highest load in the whole arm — the weight of everything from the upper arm outward — so it is one of the chunkier prints.',
        remove='The upper arm loses its pivot and drops.'),
    'upper_arm_so101_v1': dict(PRINTED_COMMON, name='Upper arm',
        what='The long link between shoulder and elbow. The elbow servo sits in a pocket at its far end.',
        why='Its length sets the arm\'s reach. Make it longer and the arm reaches further but every joint needs more torque to hold it up.',
        remove='No connection between shoulder and elbow — the arm ends at the shoulder.'),
    'under_arm_so101_v1': dict(PRINTED_COMMON, name='Lower arm',
        what='The forearm link from elbow to wrist. Hollow to save weight, with the wrist-flex servo pocket at the end.',
        why='Weight out here costs the most torque at the shoulder, which is why it is the most hollowed-out part.',
        remove='Elbow to wrist connection gone; the wrist and gripper fall away.'),
    'motor_holder_so101_wrist_v1': dict(PRINTED_COMMON, name='Wrist motor holder',
        what='Cradle that clamps the wrist-flex servo into the end of the lower arm.',
        why='The wrist servo bears sideways loads when the gripper twists; this cradle holds its body so the gears do not.',
        remove='The wrist-flex servo would slide out of the forearm.'),
    'wrist_roll_pitch_so101_v2': dict(PRINTED_COMMON, name='Wrist',
        what='The wrist block. It is driven by the wrist-flex servo and carries the wrist-roll servo (the one without a horn) pointing along the arm.',
        why='Two axes meet here: flex (up/down) and roll (twist). Packing both into 6 cm is why this is the most detailed print.',
        remove='No wrist — the gripper cannot tilt or twist, it just points where the forearm points.'),
    'wrist_roll_follower_so101_v1': dict(PRINTED_COMMON, name='Gripper body (fixed jaw)',
        what='The gripper housing and the fixed finger. It bolts to the wrist-roll servo horn and holds the gripper servo.',
        why='The fixed jaw is the anvil; the moving jaw closes against it. Rolling this whole block is what lets the gripper approach objects from any angle.',
        remove='No fixed finger — the moving jaw has nothing to squeeze against, so it cannot hold anything.'),
    'moving_jaw_so101_v1': dict(PRINTED_COMMON, name='Moving jaw',
        what='The finger that opens and closes. It is bolted straight to the gripper servo horn.',
        why='Servo-driven jaw means grip force is set in software by limiting the servo\'s load — good for not crushing things.',
        remove='The gripper cannot close.'),
    'waveshare_mounting_plate_so101_v2': dict(PRINTED_COMMON, name='Control board mounting plate',
        what='A small printed plate that fastens the Waveshare servo driver board to the side of the base.',
        why='Keeps the board and its USB/power connectors fixed so cables are not yanked when the arm moves.',
        remove='The driver board dangles on its cables; nothing else changes.'),
}

# Parts that are real but not in the CAD: electronics, cables, fasteners, tools.
EXTRA = [
    dict(id='waveshare_board', name='Waveshare Bus Servo Adapter (A)', short='Servo driver board', category='electronics', qty=1, mass_g=15, price_usd=10.6,
        made_of='PCB with USB-C, DC jack, serial bus header',
        what='The bridge between the computer and the servos. It takes USB from your laptop and 5–12 V from the power supply and puts both onto the three-wire servo bus.',
        why='All six servos daisy-chain onto one cable that ends here. One board, one USB port, one power jack — that is the entire wiring of the arm.',
        spec=[['Input', 'USB-C data + 5–12 V DC power'], ['Output', 'TTL and RS485 servo bus headers'], ['Servos supported', 'up to 253 on one bus'], ['Size', '≈ 50 × 40 mm']],
        inside=[['USB-to-UART chip', 'Turns USB into a plain serial stream the servos understand (typically a CH343-class converter).'],
                ['Bus buffer / level shifter', 'Drives the single half-duplex servo data line so several servos can share it without shouting over each other.'],
                ['Power path', 'A DC barrel jack, a switch and a fuse-sized trace deliver motor current straight to the bus — the USB side never carries motor power.'],
                ['Status LEDs', 'Power and data-activity indicators.']],
        remove='The arm is a sculpture. No commands reach the servos and no power does either.',
        buy='https://www.amazon.com/Waveshare-Integrates-Control-Circuit-Supports/dp/B0CTMM4LWK/', placement='board'),
    dict(id='power_supply', name='Power supply 5 V, 5 A (barrel jack)', short='Power supply', category='electronics', qty=1, mass_g=120, price_usd=10,
        made_of='Switch-mode wall adapter', what='Wall adapter that powers the servos through the driver board.',
        why='USB alone gives 0.5–0.9 A; six servos can pull several amps when they stall, so motor power comes from here.',
        spec=[['Output', '5 V DC, 5 A (use 12 V 5 A+ for 12 V servos)'], ['Connector', '5.5 × 2.1 mm barrel']],
        remove='Servos brown out and reset the moment they push against anything.', buy='https://www.amazon.com/Facmogu-Switching-Transformer-Compatible-5-5x2-1mm/dp/B087LY41PV/', shown=False),
    dict(id='usb_cable', name='USB-C cable', short='USB cable', category='electronics', qty=1, mass_g=30, price_usd=7,
        made_of='Copper, braided jacket', what='Carries commands from the computer to the driver board and sensor readings back.',
        why='Position, load and temperature of all six servos stream back over this one cable at 1 Mbps.',
        remove='No control from the computer; the servos hold their last position.', buy='https://www.amazon.com/Charging-etguuds-Charger-Braided-Compatible/dp/B0B8NWLLW2/', shown=False),
    dict(id='servo_cables', name='3-pin servo bus cables', short='Servo cables', category='electronics', qty=6, mass_g=4, price_usd=0,
        made_of='3-wire JST-style leads (power, ground, data)', what='Short daisy-chain leads from servo to servo. They ship in the servo box.',
        why='Because the bus is daisy-chained there are only six short cables in the whole arm, routed through the hollow printed links.',
        remove='Every servo past the missing cable goes dark.', shown=False),
    dict(id='servo_screws', name='Servo screws (ship with the servos)', short='Screws', category='fastener', qty=6, mass_g=6, price_usd=0,
        made_of='Steel', what='Each servo comes with a bag: small self-tapping screws for its body, screws for the horn, and a centre screw that locks the horn to the shaft.',
        why='Every printed part attaches with these. No glue, no nuts — screws bite straight into the plastic.',
        spec=[['Body screws', 'small self-tapping, 4 per servo'], ['Horn screws', 'attach printed brackets to the splined horn'], ['Centre screw', 'one per horn, locks it to the shaft']],
        remove='Parts separate under load. Losing the centre screw is the classic failure: the horn slips and the joint reads the wrong angle.', shown=False),
    dict(id='table_clamp', name='Table clamps', short='Clamp', category='tool', qty=2, mass_g=150, price_usd=5,
        made_of='Steel/plastic', what='Woodworking clamps that pin the base to the table edge.',
        why='The arm weighs about 600 g but can lever itself over when extended; the clamp is what lets it push and pull on things.',
        remove='The arm walks itself off the table the first time it reaches out.', buy='https://www.amazon.com/Mr-Pen-Carpenter-Clamp-6inch/dp/B092L925J4/', shown=False),
]

JOINTS = {
    'shoulder_pan':  ('Shoulder pan',  'Turns the whole arm left and right on the base.'),
    'shoulder_lift': ('Shoulder lift', 'Raises and lowers the upper arm. The hardest-working joint: it lifts everything beyond it.'),
    'elbow_flex':    ('Elbow',         'Bends the forearm toward or away from the upper arm.'),
    'wrist_flex':    ('Wrist flex',    'Tilts the gripper up and down.'),
    'wrist_roll':    ('Wrist roll',    'Twists the gripper about the forearm axis so it can approach from any angle.'),
    'gripper':       ('Gripper',       'Opens and closes the moving jaw.'),
}
